import os
import json
import zipfile
from datetime import datetime
from typing import List, Dict, Any

class SkillEngine:
    """
    Project Epsilon: Cognitive Operational Excellence Hub
    Goal: Optimizing organizational throughput via real-time realization crystallization.
    Features: Automated skill detection and .skill file generation.
    """
    def __init__(self, skill_dir: str = "layers/layer_2_core"):
        self.skill_dir = skill_dir
        os.makedirs(self.skill_dir, exist_ok=True)

    def detect_and_generate_skills(self, realizations: List[Any]):
        """
        Detects potential skills from a list of realizations and generates .skill files.
        """
        print(f"🛠️ Scanning {len(realizations)} realizations for emergent skills...")
        generated_skills = []

        for r in realizations:
            # Detection logic: Layer 0 or high Q with generic content
            if r.q_score > 1.20 or (r.layer == 0 and r.q_score > 1.10):
                skill_name = self._sanitize_name(r.content)
                if self._generate_skill_package(skill_name, r):
                    generated_skills.append(skill_name)

        return generated_skills

    def _sanitize_name(self, content: str) -> str:
        # Extract a name-like string from content
        clean = content.split(":")[1].strip() if ":" in content else content
        clean = clean.replace(" ", "-").lower()[:30]
        return "".join(c for c in clean if c.isalnum() or c == "-").strip("-")

    def _generate_skill_package(self, name: str, realization: Any) -> bool:
        path = os.path.join(self.skill_dir, f"{name}.skill")
        if os.path.exists(path):
            return False

        print(f"📦 Generating Skill Package: {name}")

        # Temporary directory for packaging
        tmp_dir = f"tmp_skill_{name}"
        os.makedirs(tmp_dir, exist_ok=True)
        os.makedirs(os.path.join(tmp_dir, "scripts"), exist_ok=True)
        os.makedirs(os.path.join(tmp_dir, "references"), exist_ok=True)
        os.makedirs(os.path.join(tmp_dir, "templates"), exist_ok=True)

        # 1. SKILL.md
        md_content = f"""---
name: {name}
description: "Crystallized skill from realization: {realization.content}"
q_score: {realization.q_score:.4f}
---

# {name.replace('-', ' ').title()}

This skill was autonomously generated by Project Epsilon.

## Realization Context
- **Content**: {realization.content}
- **Layer**: {realization.layer}
- **Timestamp**: {getattr(realization, 'timestamp', datetime.now().isoformat())}

## Usage
Automatically invoked when system identifies patterns matching {name}.
"""
        with open(os.path.join(tmp_dir, "SKILL.md"), "w") as f:
            f.write(md_content)

        # 2. scripts/example.py
        py_content = f"""# Autogenerated implementation for {name}
def execute():
    print("Executing {name} implementation...")
    # Based on Q={realization.q_score}
    return True
"""
        with open(os.path.join(tmp_dir, "scripts/example.py"), "w") as f:
            f.write(py_content)

        # Create ZIP
        with zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for root, dirs, files in os.walk(tmp_dir):
                for file in files:
                    zipf.write(os.path.join(root, file),
                               os.path.relpath(os.path.join(root, file), tmp_dir))

        # Cleanup
        import shutil
        shutil.rmtree(tmp_dir)
        return True

if __name__ == "__main__":
    from layers.layer_2_core.realization_engine import Realization, RealizationFeatures

    engine = SkillEngine()
    test_r = Realization(
        id="R_TEST",
        content="Universal Logic: Recursive ensembling of diverse reasoning paths.",
        layer=0,
        features=RealizationFeatures(0.99, 0.99, 0.99, 0.99, 0.99, 0.99),
        q_score=1.3499,
        turn_number=1,
        timestamp=datetime.now().isoformat(),
        parents=[],
        children=[]
    )

    skills = engine.detect_and_generate_skills([test_r])
    print(f"✅ Generated Skills: {skills}")
